### ISSUE TITLE
"'Database' object has no attribute 'get_connection'" errors

### ISSUE THREAD

**Issue by Eterance** [HKUNLP/Binder#1]
Hi, when I run the "wikitq nsql annotation command" with following commands,
```
cd Binder

export TOKENIZERS_PARALLELISM=false

nohup  python scripts/annotate_binder_program.py --dataset wikitq \
 --dataset_split test \
 --prompt_file templates/prompts/wikitq_binder.txt \
 --n_parallel_prompts 1 \
 --max_generation_tokens 512 \
 --temperature 0.4 \
 --sampling_n 20 \
 -v \
> run-wikitq-annotation.out 2>&1 &

tail -fn 5000 run-wikitq-annotation.out
```
(I didn't run `run.py` directly, because it reports an error: `python: can't open file '/scripts/annotate_binder_program.py': [Errno 2] No such file or directory`)

the console outputs the following message:
![image](https://user-images.githubusercontent.com/25473156/204136663-10b78b25-0067-4a85-bd6e-6c591a3fec90.png)

I located the code that threw the error: 
`self.records_conn = self.db.get_connection()` at line 100, nsql/database.py

![image](https://user-images.githubusercontent.com/25473156/204136996-edf170d5-d0c3-415f-80e2-f5502b22485d.png)

I haven't completed the test yet, but I'm wondering if this whole bunch of `'Database' object has no attribute 'get_connection'` errors is normal? How should I fix it?

**Comment by Timothyxxx** [comment]
Hi, 

Thanks for your question!
It is undoubtedly abnormal to see this error, could you double-check your pip packages about the version of `records`? It should be strictly the same as us or throw similar errors as I remembered.

Thanks!

**Comment by Eterance** [comment]
Thank you for your reply!

The version of `records` in my env is `0.5.2`. 

It seems that the `py3.7binder.yaml` file you provided does not mention the version of `records`. Which version should I install?
![image](https://user-images.githubusercontent.com/25473156/204540109-841dcd3e-aef6-4141-9b00-2d3258769dfb.png)

**Comment by Timothyxxx** [comment]
I just checked that mine is 0.5.3, I can really remember if it is the case, could you have a try on your side?

**Comment by Timothyxxx** [comment]
I saw similar things in https://github.com/eguilg/nl2sql/issues/1 when I first met that problem months before, so I record that in our README.md and fix that, you can see this instruction here https://github.com/HKUNLP/Binder#dependencies

**Comment by Timothyxxx** [comment]
`records==0.5.3` will save you from struggling and see magic of Binder🔗～

**Comment by Eterance** [comment]
Sorry, my mistake, I forgot to run `pip install records==0.5.3` after creating the environment. 😂 It actually works like magic.

Thanks again for your patience!

**Comment by Timothyxxx** [comment]
Thank you for asking!
