### ISSUE TITLE
File location for "binder_program_wikitq_test_exec.json"

### ISSUE THREAD

**Issue by Chenhao-Huang** [HKUNLP/Binder#4]
Hi there, 

I was wondering where I can find "binder_program_wikitq_test_exec.json" file, mentioned in the following command.

Thanks a lot.

=======================
"wikitq nsql execution command"
os.system(fr"""{TOKENIZER_FALSE}python {ROOT_DIR}/scripts/execute_binder_program.py --dataset wikitq \
--dataset_split test \
--qa_retrieve_pool_file templates/qa_retrieve_pool/qa_retrieve_pool.json \
--input_program_file binder_program_wikitq_test.json \
--output_program_execution_file binder_program_wikitq_test_exec.json \
--vote_method simple
""")

**Comment by Timothyxxx** [comment]
Hi, thanks for asking.
`binder_program_wikitq_test_exec.json` is the output file that create result(by executing the sqls and ensemble the executed results) from `binder_program_wikitq_test.json` file.

**Comment by Timothyxxx** [comment]
We name the whole process into two steps: `annotate` to get binder program (nsqls / npythons); `execute` to execute the programs on database and ensemble the results by voting to get final result.

**Comment by Chenhao-Huang** [comment]
Ok. I see. Thanks.
