### ISSUE TITLE
GPT-3.5-turbo experiments

### ISSUE THREAD

**Issue by devnkong** [HKUNLP/Binder#6]
Thanks for the nice work! 

Also are we still expecting updated results rerun on GPT-3.5-turbo? Looking forward to it.

**Comment by Timothyxxx** [comment]
Hi, sorry for the waiting, I am quite busy these days. Would you mind if I rerun the exps and make ChatGPT and GPT-4 as backends in late this month?

**Comment by Timothyxxx** [comment]
Or if it is convenient for you to run, I can provide helps in handle any problems you make if you like!

**Comment by devnkong** [comment]
Thanks Tianbao. No worries take your time.

**Comment by devnkong** [comment]
Also BTW, would it be convenient for you to also share the code that does Codex-end-to-end and Codex-SQL in the experiments? Thanks.

**Comment by Timothyxxx** [comment]
Thanks! We didn't save the code for that. I think for end2end, it is quite easy to do. and for SQL, since SQL is a special case for NSQL (Binder-SQL), you can run that by just modify our prompt.

**Comment by devnkong** [comment]
Thank you. As prompts can be really important to the performance of LLMs, would it be okay that you share the prompts you used towards the two cases, if you still have them?

**Comment by Timothyxxx** [comment]
Sure! You can try put [these](https://drive.google.com/drive/folders/1DD9RJOULlxHPDD_jePPOiCO4PeEt8Wf6?usp=sharing) under the template file, and then change file path in the annotate script

**Comment by yujianll** [comment]
Thanks for sharing the code!
I wonder if there is any updates on the results of ChatGPT?

**Comment by Timothyxxx** [comment]
Oh, sorry for the delay, I will run it now!

**Comment by Timothyxxx** [comment]
Hi, the result of ChatGPT serve as engine on the WikiTQ test is 2410/4344=55.5

**Comment by Timothyxxx** [comment]
@devnkong @yujianll

**Comment by Timothyxxx** [comment]
Do you also need results on TabFact and MMQA?

**Comment by yujianll** [comment]
Thanks for the updates! So it seems that using ChatGPT as the engine results in a worse performance than Codex?

**Comment by Timothyxxx** [comment]
Yes, but IMO mainly due to the limitation of the context length, rate limit and inference speed of ChatGPT, we can only sample fewer examples during generation, I set the hyper-parameter to the maximum for `gpt-3.5-turbo`, which is:

| | Codex | ChatGPT |
|---|---|---|
| Context length | ~8000 | ~4000 |
|number of sampled examples of Binder program | 20 | 5 | 
|in-context learning examples of Binder program | 14 | 8 |
 
 I can run more wild settings after OpenAI loosen their control of limits as before

**Comment by Timothyxxx** [comment]
You can also run GPT-4 if you have enough budget(

**Comment by devnkong** [comment]
Thanks for the updates! BTW did you try `gpt-3.5-turbo-16k`? Also currently how did you do majority vote? We can no longer access the token probabilities.

**Comment by Timothyxxx** [comment]
We didn't try `gpt-3.5-turbo-16k`, and I think we can try later. As you mentioned, we don't have token probabilities anymore from OpenAI, so we just have the same weight for every sampled generation result.

**Comment by devnkong** [comment]
Thanks, so for the voting, which voting method is used? I see in your code you have several options, like `simple`, `prob`, etc.

**Comment by devnkong** [comment]
Also did you try 1 sample per generation? (no voting)

**Comment by Timothyxxx** [comment]
For the original paper results got during April to September of 2022, we use `prob`, since it leads to slightly higher results (about 1 percent as I remember). But I think it's not a big deal today about which one you are using.

**Comment by Timothyxxx** [comment]
Yes, we tried that, just set the n_sample to 1, but the results will be lower for a little bit as well.
